### ISSUE TITLE
钉钉、微信不拆包

### ISSUE THREAD

**Issue by B0luo** [B0y1n4o4/LuckyMoney#1]
设备：小米9 android10 MIUI11 
选项已勾，一直弹出红包但是不拆包

**Comment by B0y1n4o4** [comment]
@B0luo  个人以华为手机 EMUI 系统做适配，小米 MIUI 系统一直都有这个问题，只点击红包，不拆开。近期会适配小米系统。
PS: 自动收账功能是否能正常点击？

**Comment by B0luo** [comment]
> @ B0luo 个人以华为手机EMUI系统做适当的调整，小米MIUI系统一直都有这个问题，只点击红包，不拆开。近期会适应小米系统
> 。PS：自动收账功能是否能正常点击？

谢谢作者解答，没有用到自动收账功能。改天测试一下。期待新版本推出。

**Comment by newpurr** [comment]
设备：红米K20 PRO android10 MIUI11
选项已勾，一直弹出红包但是不拆红包，作者能不能帮忙修复下，谢谢

**Comment by B0y1n4o4** [comment]
@B0luo @SuperHappysir    MIUI 11 拆包问题已修复，前往链接下载
[1.0.4 版本](https://github.com/B0y1n4o4/LuckyMoney/releases/tag/v1.0.4)

**Comment by B0luo** [comment]
> @ B0luo @SuperHappysir MIUI 11拆包问题已修复，前往链接下载
> [1.0.4版本](https://github.com/B0y1n4o4/LuckyMoney/releases/tag/v1.0.4)

谢谢，测试已经可以。祝作者新年快乐~~

**Comment by B0luo** [comment]
> @ B0luo 个人以华为手机EMUI系统做适当的调整，小米MIUI系统一直都有这个问题，只点击红包，不拆开。近期会适应小米系统
> 。PS：自动收账功能是否能正常点击？

先赞赏一下，后面好用请作者喝咖啡
