### ISSUE TITLE
钉钉不拆包问题

### ISSUE THREAD

**Issue by B0luo** [B0y1n4o4/LuckyMoney#2]
钉钉进入聊天页面，弹出红包但不自动拆包。我的设备是小米 MIUI11 安卓10  ，作者能否看一下，年会将至 /哭

**Comment by B0y1n4o4** [comment]
我这边测过了，小米 MIUI11 是可以领的。
钉钉抢还是有一定的BUG的，因为和微信不一样，无法判断是否领过，没有任何标识，例如：
- 自己没领到的红包会重复领（年会如果大家刷屏一下子刷过去那就还好）
- 自己发的也会重复领
